### ISSUE TITLE
Scss error

### ISSUE THREAD

**Issue by dcsan** [meteoric/meteorhunt#10]
on a clean install first run

```
   While building the application:
   client/stylesheets/app.scss: Scss compiler error: undefined
   /Users/dc/dev/ref/meteorhunt/client/stylesheets/app.scss:6: file to import not
   found or unreadable:
   '.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic'
   Current dir: /Users/dc/dev/ref/meteorhunt/client/stylesheets/

```

dont suppose you guys would consider stylus instead?

**Comment by dcsan** [comment]
sass version issue

contacts> scss --version
Sass 3.2.19 (Media Mark)
contacts> gem install sass
Fetching: sass-3.4.10.gem (100%)
Successfully installed sass-3.4.10
Parsing documentation for sass-3.4.10
Installing ri documentation for sass-3.4.10
1 gem installed
contacts> scss --version  
Sass 3.4.10 (Selective Steve)
contacts> meteor

**Comment by elie222** [comment]
how did you solve this problem?

**Comment by elie222** [comment]
problem magically disappeared when i reran the meteor command

**Comment by kaushik1979** [comment]
The import paths are wrong. If you navigate to the .meteor/.../ directory, the scss files start with _. Replace your imports with the following and it should work.

@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/_ionic';
@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/_ionicons';

**Comment by dcsan** [comment]
interesting, ok. i think this just always happens with the way the build process works that after a meteor reset, the files are not there the first time the app runs, and so you have to restart.

it may also be something to do with production vs development modes, as i haven't seen the problem on production deploys. but maybe the servers in that case just automatically restart once...

**Comment by dcsan** [comment]
I actually have those @import paths. they are added to the app itself and include the package name
but this include is added to the app itself, not self-contained in a package.

i don't usually use sass - is this the normal way to do it? seems incredibly fragile.

**Comment by kaushik1979** [comment]
I am not sure. I read that somewhere in the documents. But I had the same issue as you and was able to figure out how to specify the correct path.

**Comment by dcsan** [comment]
https://github.com/meteoric/ionic-sass#customization
