### ISSUE TITLE
oauth2 authentification with meteor dev account

### ISSUE THREAD

**Issue by jeangui** [meteoric/meteorhunt#13]
Hello,

I have managed to deploy the application on meteorhunt-jgl.meteor.com but my oauth2 mechanism does not work.
I did insert in settings.json the information I got from the https://www.meteor.com/account-settings/apps web site (I have created a meteorhunt application with the http://meteorhunt-jgl.meteor.com redirent url and I use the app id and app secret as the client id and the secret respectively).

when I try to log into the application (tab 3 and 4) and get the following error:

`Something went wrong: Invalid redirect URI [400]`

and nothing in the galaxy server logs.

thanks.

regards

**Comment by mountainash** [comment]
I'm having the same issue.

**Comment by nickw** [comment]
The redirect URL you configure [here](https://www.meteor.com/account-settings/apps) needs to have the path `_oauth/meteor-developer?close` at the end of it.

**Comment by jeangui** [comment]
perfect. it works fine now. :)
thanks a lot.
