### ISSUE TITLE
Tweaking profile to show products created

### ISSUE THREAD

**Issue by malcolmevans** [meteoric/meteorhunt#14]
Hey Nick,

Thanks a ton for making this! Newbie question here:

How can I tweak the profiles to show both products a person creates & the ones they have voted on?

Thanks!

**Comment by nickw** [comment]
Change this line: https://github.com/meteoric/meteorhunt/blob/master/server/publications.js#L55 to something like this:

```
return Products.find({$or:[{_id: {$in: user.profile.votedProductIds}}, {userId: user._id}]});
```

**Comment by malcolmevans** [comment]
Thank you, Nick.

I've been toying with it for the past few hours but to no avail. I've added that logic, but it seems like I need to make an adjustment to this line: https://github.com/meteoric/meteorhunt/blob/master/both/collections/users.js#L7

But unfortunately adding the {userId: user._id} doesn't update what shows.
