### ISSUE TITLE
Refreshing triggers bugs

### ISSUE THREAD

**Issue by benstr** [meteoric/meteorhunt#3]
When refreshing the bottom navbar resets the active class to **Trending** page. 

When refreshing while on  **Notifications** or **Profile** pages Log-In modal pops up whether you are logged in or not. Should only show when not logged in.

**Comment by nickw** [comment]
Ah right:
1. Re: refreshing…we need to figure out a way to "activate" the current tab when the page loads. Currently the tab is activated when it is clicked: https://github.com/meteoric/meteor-ionic/blob/master/components/ionTab/ionTab.js#L2. And I just put in an ugly hack to activate the first tab when the app loads: https://github.com/meteoric/meteorhunt/blob/master/client/templates/layouts/appLayout.js#L2
2. Re: login modals. I think we just need to check `Meteor.loggingIn()`

**Comment by benstr** [comment]
It is less elegant but what if we just set the `currentTab` session in the route's action hook?

**Comment by davidwoody** [comment]
Fixed in this commit - https://github.com/meteoric/meteor-ionic/commit/e6e53d62b9d162009b5c7a5d38783d15413878db
