### ISSUE TITLE
Something went wrong: that application does not exist. Error

### ISSUE THREAD

**Issue by halilertekin** [meteoric/meteorhunt#8]
=> Errors prevented startup:

   While building the application:
   client/stylesheets/app.scss: Scss compiler error: undefined
   /Users/xxx/ionic/meteorhunt/client/stylesheets/app.scss:6: file to
   import not found or unreadable:
   '.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic'
   Current dir: /Users/xxx/ionic/meteorhunt/client/stylesheets/

=> Your application has errors. Waiting for file change.
^Cfish: Job 1, 'meteor --settings settings.json' terminated by signal SIGINT (Quit request from job control (^C))

**Comment by nickw** [comment]
Yeah, unfortunately that happens the first time you start up any meteor-ionic app. Just `ctrl-C` and start it up again and it will work.

See https://github.com/meteor/meteor/issues/2606 and https://github.com/meteor/meteor/issues/2796
